Traceback (most recent call last):
  File "/home/runner/.virtualenvs/draco-2B3Fy6YM-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.virtualenvs/draco-2B3Fy6YM-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.virtualenvs/draco-2B3Fy6YM-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.virtualenvs/draco-2B3Fy6YM-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/.virtualenvs/draco-2B3Fy6YM-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.virtualenvs/draco-2B3Fy6YM-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.virtualenvs/draco-2B3Fy6YM-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from draco import dict_union, dict_to_facts, check_spec, get_violations


def show(*args):
    spec = dict_union(*args)
    prog = dict_to_facts(spec)
    if not check_spec(prog):
        print("\n".join(prog))
        print(get_violations(prog))
        assert False, "Invalid spec"
    return prog
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdraco[39;00m [38;5;28;01mimport[39;00m dict_union, dict_to_facts, check_spec, get_violations
[1;32m      4[0m [38;5;28;01mdef[39;00m [38;5;21mshow[39m([38;5;241m*[39margs):
[1;32m      5[0m     spec [38;5;241m=[39m dict_union([38;5;241m*[39margs)

[0;31mImportError[0m: cannot import name 'check_spec' from 'draco' (/home/runner/work/draco2/draco2/draco/__init__.py)
ImportError: cannot import name 'check_spec' from 'draco' (/home/runner/work/draco2/draco2/draco/__init__.py)

